name: Build and Deploy Documentation
on:
  push:
    branches:
      - develop

jobs:
  create_documentation:
    runs-on: ubuntu-latest
    name: Deploy documentation

    steps:

    - name: Install ubuntu dependencies
      run: |
        sudo apt-get install libproj-dev proj-data proj-bin
        sudo apt-get install libgeos-dev musl-dev libc-dev
        sudo ln -s /usr/lib/x86_64-linux-musl/libc.so /lib/libc.musl-x86_64.so.1

    - name: Install (upgrade) dependencies
      run: |
        pip install --upgrade pip
        pip install pdoc

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install emcpy
      run: |
        pip install .

    - name: Generate documentation
      run: |
        pdoc --docformat "google" -o docs emcpy
        ls -lR docs/

    - name: Deploy documentation
      uses: ammaraskar/sphinx-action@master
      with:
        branch: gh-pages
        folder: docs
